// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The base message to load configs from file.
type Config struct {
	Tls                  string   `protobuf:"bytes,1,opt,name=tls,proto3" json:"tls,omitempty"`
	CertFile             string   `protobuf:"bytes,2,opt,name=certFile,proto3" json:"certFile,omitempty"`
	KeyFile              string   `protobuf:"bytes,3,opt,name=keyFile,proto3" json:"keyFile,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	DbUser               string   `protobuf:"bytes,5,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbPass               string   `protobuf:"bytes,6,opt,name=db_pass,json=dbPass,proto3" json:"db_pass,omitempty"`
	DbName               string   `protobuf:"bytes,7,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	DbAddr               string   `protobuf:"bytes,8,opt,name=db_addr,json=dbAddr,proto3" json:"db_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetTls() string {
	if m != nil {
		return m.Tls
	}
	return ""
}

func (m *Config) GetCertFile() string {
	if m != nil {
		return m.CertFile
	}
	return ""
}

func (m *Config) GetKeyFile() string {
	if m != nil {
		return m.KeyFile
	}
	return ""
}

func (m *Config) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Config) GetDbUser() string {
	if m != nil {
		return m.DbUser
	}
	return ""
}

func (m *Config) GetDbPass() string {
	if m != nil {
		return m.DbPass
	}
	return ""
}

func (m *Config) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *Config) GetDbAddr() string {
	if m != nil {
		return m.DbAddr
	}
	return ""
}

type Amenity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl              string   `protobuf:"bytes,2,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amenity) Reset()         { *m = Amenity{} }
func (m *Amenity) String() string { return proto.CompactTextString(m) }
func (*Amenity) ProtoMessage()    {}
func (*Amenity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *Amenity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amenity.Unmarshal(m, b)
}
func (m *Amenity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amenity.Marshal(b, m, deterministic)
}
func (m *Amenity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amenity.Merge(m, src)
}
func (m *Amenity) XXX_Size() int {
	return xxx_messageInfo_Amenity.Size(m)
}
func (m *Amenity) XXX_DiscardUnknown() {
	xxx_messageInfo_Amenity.DiscardUnknown(m)
}

var xxx_messageInfo_Amenity proto.InternalMessageInfo

func (m *Amenity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Amenity) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

type Log struct {
	LastUpdated          *Timestamp `protobuf:"bytes,1,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	CreatedAt            *Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLastUpdated() *Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *Log) GetCreatedAt() *Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// Proto representation of a date. 2019-05-23 = {year: 2019 month:5 day:23}.
type Date struct {
	Year int32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	// Month as would be written on a string. 1-indexed so Jan = 1.
	Month int32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	// Month as would be written on a string. 1-indexed so 01 = 1.
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Timezone             string   `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *Date) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type DateTime struct {
	Date                 *Date    `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Time                 *Time    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateTime) Reset()         { *m = DateTime{} }
func (m *DateTime) String() string { return proto.CompactTextString(m) }
func (*DateTime) ProtoMessage()    {}
func (*DateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *DateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateTime.Unmarshal(m, b)
}
func (m *DateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateTime.Marshal(b, m, deterministic)
}
func (m *DateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateTime.Merge(m, src)
}
func (m *DateTime) XXX_Size() int {
	return xxx_messageInfo_DateTime.Size(m)
}
func (m *DateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_DateTime.DiscardUnknown(m)
}

var xxx_messageInfo_DateTime proto.InternalMessageInfo

func (m *DateTime) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *DateTime) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

// Proto representation of a time. 23:05:06 = {hour:23 minutes:5 second: 6}.
type Time struct {
	Hours                int32    `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes              int32    `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	Seconds              int32    `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{5}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetHours() int32 {
	if m != nil {
		return m.Hours
	}
	return 0
}

func (m *Time) GetMinutes() int32 {
	if m != nil {
		return m.Minutes
	}
	return 0
}

func (m *Time) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{6}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type Price struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	BasePrice            float32  `protobuf:"fixed32,2,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	CleaningFee          float32  `protobuf:"fixed32,3,opt,name=cleaning_fee,json=cleaningFee,proto3" json:"cleaning_fee,omitempty"`
	ExtraPersonFee       float32  `protobuf:"fixed32,4,opt,name=extra_person_fee,json=extraPersonFee,proto3" json:"extra_person_fee,omitempty"`
	WeeklyPriceFactor    float32  `protobuf:"fixed32,5,opt,name=weekly_price_factor,json=weeklyPriceFactor,proto3" json:"weekly_price_factor,omitempty"`
	MontlyPriceFactor    float32  `protobuf:"fixed32,6,opt,name=montly_price_factor,json=montlyPriceFactor,proto3" json:"montly_price_factor,omitempty"`
	SecurityDepositFee   float32  `protobuf:"fixed32,7,opt,name=security_deposit_fee,json=securityDepositFee,proto3" json:"security_deposit_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{7}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Price) GetBasePrice() float32 {
	if m != nil {
		return m.BasePrice
	}
	return 0
}

func (m *Price) GetCleaningFee() float32 {
	if m != nil {
		return m.CleaningFee
	}
	return 0
}

func (m *Price) GetExtraPersonFee() float32 {
	if m != nil {
		return m.ExtraPersonFee
	}
	return 0
}

func (m *Price) GetWeeklyPriceFactor() float32 {
	if m != nil {
		return m.WeeklyPriceFactor
	}
	return 0
}

func (m *Price) GetMontlyPriceFactor() float32 {
	if m != nil {
		return m.MontlyPriceFactor
	}
	return 0
}

func (m *Price) GetSecurityDepositFee() float32 {
	if m != nil {
		return m.SecurityDepositFee
	}
	return 0
}

type Address struct {
	Apt                  string   `protobuf:"bytes,1,opt,name=apt,proto3" json:"apt,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Street               string   `protobuf:"bytes,6,opt,name=street,proto3" json:"street,omitempty"`
	Country              string   `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Zipcode              string   `protobuf:"bytes,8,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	Neighborhood         string   `protobuf:"bytes,9,opt,name=neighborhood,proto3" json:"neighborhood,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{8}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetApt() string {
	if m != nil {
		return m.Apt
	}
	return ""
}

func (m *Address) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Address) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

func (m *Address) GetNeighborhood() string {
	if m != nil {
		return m.Neighborhood
	}
	return ""
}

type Picture struct {
	LargeUrl             string   `protobuf:"bytes,1,opt,name=large_url,json=largeUrl,proto3" json:"large_url,omitempty"`
	RegularUrl           string   `protobuf:"bytes,2,opt,name=regular_url,json=regularUrl,proto3" json:"regular_url,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{9}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetLargeUrl() string {
	if m != nil {
		return m.LargeUrl
	}
	return ""
}

func (m *Picture) GetRegularUrl() string {
	if m != nil {
		return m.RegularUrl
	}
	return ""
}

func (m *Picture) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Picture) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type Listing struct {
	// @inject_tag: sql:”primary_key”
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: sql:"notnull,default:0"
	Beds                 int32      `protobuf:"varint,2,opt,name=beds,proto3" json:"beds,omitempty"`
	Tags                 string     `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	Type                 string     `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	TermsMaxnights       string     `protobuf:"bytes,5,opt,name=terms_maxnights,json=termsMaxnights,proto3" json:"terms_maxnights,omitempty"`
	TermsMinnights       string     `protobuf:"bytes,6,opt,name=terms_minnights,json=termsMinnights,proto3" json:"terms_minnights,omitempty"`
	TermsCancellation    string     `protobuf:"bytes,7,opt,name=terms_cancellation,json=termsCancellation,proto3" json:"terms_cancellation,omitempty"`
	Title                string     `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Active               bool       `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	Price                *Price     `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	Address              *Address   `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	Bedtype              string     `protobuf:"bytes,12,opt,name=bedtype,proto3" json:"bedtype,omitempty"`
	Pictures             []*Picture `protobuf:"bytes,13,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Bedrooms             int32      `protobuf:"varint,14,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms            int32      `protobuf:"varint,15,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	Islisted             bool       `protobuf:"varint,16,opt,name=islisted,proto3" json:"islisted,omitempty"`
	Nickname             string     `protobuf:"bytes,17,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Timezone             string     `protobuf:"bytes,18,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Accomodates          int32      `protobuf:"varint,21,opt,name=accomodates,proto3" json:"accomodates,omitempty"`
	AllowsPets           bool       `protobuf:"varint,22,opt,name=allows_pets,json=allowsPets,proto3" json:"allows_pets,omitempty"`
	AllowsEvents         bool       `protobuf:"varint,23,opt,name=allows_events,json=allowsEvents,proto3" json:"allows_events,omitempty"`
	AllowsInfants        bool       `protobuf:"varint,24,opt,name=allows_infants,json=allowsInfants,proto3" json:"allows_infants,omitempty"`
	AllowsSmoking        bool       `protobuf:"varint,25,opt,name=allows_smoking,json=allowsSmoking,proto3" json:"allows_smoking,omitempty"`
	AllowsChildren       bool       `protobuf:"varint,26,opt,name=allows_children,json=allowsChildren,proto3" json:"allows_children,omitempty"`
	DefaultCheckInTime   *Time      `protobuf:"bytes,27,opt,name=default_check_in_time,json=defaultCheckInTime,proto3" json:"default_check_in_time,omitempty"`
	DefaultCheckOutTime  *Time      `protobuf:"bytes,28,opt,name=default_check_out_time,json=defaultCheckOutTime,proto3" json:"default_check_out_time,omitempty"`
	Amenities            []*Amenity `protobuf:"bytes,29,rep,name=amenities,proto3" json:"amenities,omitempty"`
	AmenitiesNotIncluded []*Amenity `protobuf:"bytes,30,rep,name=amenities_not_included,json=amenitiesNotIncluded,proto3" json:"amenities_not_included,omitempty"`
	Log                  *Log       `protobuf:"bytes,100,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{10}
}

func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Listing) GetBeds() int32 {
	if m != nil {
		return m.Beds
	}
	return 0
}

func (m *Listing) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Listing) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Listing) GetTermsMaxnights() string {
	if m != nil {
		return m.TermsMaxnights
	}
	return ""
}

func (m *Listing) GetTermsMinnights() string {
	if m != nil {
		return m.TermsMinnights
	}
	return ""
}

func (m *Listing) GetTermsCancellation() string {
	if m != nil {
		return m.TermsCancellation
	}
	return ""
}

func (m *Listing) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Listing) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Listing) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Listing) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Listing) GetBedtype() string {
	if m != nil {
		return m.Bedtype
	}
	return ""
}

func (m *Listing) GetPictures() []*Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *Listing) GetBedrooms() int32 {
	if m != nil {
		return m.Bedrooms
	}
	return 0
}

func (m *Listing) GetBathrooms() int32 {
	if m != nil {
		return m.Bathrooms
	}
	return 0
}

func (m *Listing) GetIslisted() bool {
	if m != nil {
		return m.Islisted
	}
	return false
}

func (m *Listing) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Listing) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Listing) GetAccomodates() int32 {
	if m != nil {
		return m.Accomodates
	}
	return 0
}

func (m *Listing) GetAllowsPets() bool {
	if m != nil {
		return m.AllowsPets
	}
	return false
}

func (m *Listing) GetAllowsEvents() bool {
	if m != nil {
		return m.AllowsEvents
	}
	return false
}

func (m *Listing) GetAllowsInfants() bool {
	if m != nil {
		return m.AllowsInfants
	}
	return false
}

func (m *Listing) GetAllowsSmoking() bool {
	if m != nil {
		return m.AllowsSmoking
	}
	return false
}

func (m *Listing) GetAllowsChildren() bool {
	if m != nil {
		return m.AllowsChildren
	}
	return false
}

func (m *Listing) GetDefaultCheckInTime() *Time {
	if m != nil {
		return m.DefaultCheckInTime
	}
	return nil
}

func (m *Listing) GetDefaultCheckOutTime() *Time {
	if m != nil {
		return m.DefaultCheckOutTime
	}
	return nil
}

func (m *Listing) GetAmenities() []*Amenity {
	if m != nil {
		return m.Amenities
	}
	return nil
}

func (m *Listing) GetAmenitiesNotIncluded() []*Amenity {
	if m != nil {
		return m.AmenitiesNotIncluded
	}
	return nil
}

func (m *Listing) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "proto.Config")
	proto.RegisterType((*Amenity)(nil), "proto.Amenity")
	proto.RegisterType((*Log)(nil), "proto.Log")
	proto.RegisterType((*Date)(nil), "proto.Date")
	proto.RegisterType((*DateTime)(nil), "proto.DateTime")
	proto.RegisterType((*Time)(nil), "proto.Time")
	proto.RegisterType((*Timestamp)(nil), "proto.Timestamp")
	proto.RegisterType((*Price)(nil), "proto.Price")
	proto.RegisterType((*Address)(nil), "proto.Address")
	proto.RegisterType((*Picture)(nil), "proto.Picture")
	proto.RegisterType((*Listing)(nil), "proto.Listing")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 1144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x56, 0xef, 0x6e, 0x1c, 0x35,
	0x10, 0xd7, 0x5d, 0x72, 0xff, 0xe6, 0xae, 0x69, 0xea, 0xa6, 0xe9, 0xf6, 0x1f, 0x0d, 0x8b, 0x10,
	0x11, 0x82, 0x82, 0xe8, 0x17, 0x24, 0x24, 0x44, 0x95, 0x12, 0x29, 0x52, 0x28, 0xd1, 0x42, 0xbe,
	0xb2, 0xf2, 0xed, 0x4e, 0xf6, 0xac, 0xec, 0xda, 0x2b, 0xdb, 0xdb, 0xf6, 0xfa, 0x00, 0xbc, 0x03,
	0x1f, 0x79, 0x1b, 0x5e, 0x81, 0xb7, 0x41, 0x33, 0xf6, 0x5e, 0x2f, 0xb4, 0x9f, 0xce, 0xbf, 0x3f,
	0x1e, 0xdb, 0x33, 0x63, 0xef, 0xc1, 0xa2, 0x31, 0x25, 0xd6, 0xee, 0x59, 0x6b, 0x8d, 0x37, 0x62,
	0xc4, 0x3f, 0xe9, 0x3f, 0x03, 0x18, 0x9f, 0x18, 0x7d, 0xa5, 0x2a, 0xb1, 0x0f, 0x3b, 0xbe, 0x76,
	0xc9, 0xe0, 0x68, 0x70, 0x3c, 0xcb, 0x68, 0x28, 0x1e, 0xc2, 0xb4, 0x40, 0xeb, 0x4f, 0x55, 0x8d,
	0xc9, 0x90, 0xe9, 0x0d, 0x16, 0x09, 0x4c, 0xae, 0x71, 0xcd, 0xd2, 0x0e, 0x4b, 0x3d, 0x14, 0x02,
	0x76, 0x5b, 0x63, 0x7d, 0xb2, 0x7b, 0x34, 0x38, 0x1e, 0x65, 0x3c, 0x16, 0xf7, 0x61, 0x52, 0x2e,
	0xf3, 0xce, 0xa1, 0x4d, 0x46, 0xec, 0x1e, 0x97, 0xcb, 0x4b, 0x87, 0x36, 0x0a, 0xad, 0x74, 0x2e,
	0x19, 0xf7, 0xc2, 0x85, 0x74, 0x2e, 0x0a, 0x5a, 0x36, 0x98, 0x4c, 0x7a, 0xe1, 0x95, 0x6c, 0x30,
	0x0a, 0xb2, 0x2c, 0x6d, 0x32, 0xed, 0x85, 0x17, 0x65, 0x69, 0xd3, 0xef, 0x61, 0xf2, 0xa2, 0x41,
	0xad, 0xfc, 0x9a, 0xb6, 0xc0, 0x33, 0xc3, 0x59, 0x78, 0x2c, 0x1e, 0xc0, 0xb4, 0x36, 0x95, 0xc9,
	0x3b, 0x5b, 0xc7, 0xc3, 0x4c, 0x08, 0x5f, 0xda, 0x3a, 0xbd, 0x86, 0x9d, 0x73, 0x53, 0x89, 0xe7,
	0xb0, 0xa8, 0xa5, 0xf3, 0x79, 0xd7, 0x96, 0xd2, 0x63, 0xc9, 0xb3, 0xe7, 0xdf, 0xed, 0x87, 0x84,
	0x3d, 0xfb, 0x5d, 0x35, 0xe8, 0xbc, 0x6c, 0xda, 0x6c, 0x4e, 0xae, 0xcb, 0x60, 0x12, 0xdf, 0x00,
	0x14, 0x16, 0x69, 0x98, 0x4b, 0xcf, 0x81, 0x3f, 0x36, 0x65, 0x16, 0x3d, 0x2f, 0x7c, 0xfa, 0x07,
	0xec, 0xbe, 0x94, 0x9e, 0xd3, 0xb4, 0x46, 0x69, 0x79, 0x95, 0x51, 0xc6, 0x63, 0x71, 0x00, 0xa3,
	0xc6, 0x68, 0xbf, 0xe2, 0x38, 0xa3, 0x2c, 0x00, 0x2a, 0x4c, 0x29, 0xd7, 0x9c, 0xe6, 0x51, 0x46,
	0x43, 0x2a, 0x8c, 0x57, 0x0d, 0xbe, 0x33, 0x1a, 0x39, 0xcd, 0xb3, 0x6c, 0x83, 0xd3, 0x73, 0x98,
	0x52, 0x7c, 0x5a, 0x5b, 0x3c, 0x85, 0x5d, 0xda, 0x65, 0x3c, 0xc9, 0x3c, 0x6e, 0x8b, 0xe4, 0x8c,
	0x05, 0x32, 0xd0, 0xc4, 0xb8, 0xef, 0xf9, 0xd6, 0xbe, 0x33, 0x16, 0xd2, 0x0b, 0xd8, 0xe5, 0x48,
	0x07, 0x30, 0x5a, 0x99, 0xce, 0xba, 0xb8, 0xdd, 0x00, 0xa8, 0x09, 0x1a, 0xa5, 0x3b, 0x8f, 0x2e,
	0xee, 0xb8, 0x87, 0xa4, 0x38, 0x2c, 0x8c, 0x2e, 0x5d, 0xdc, 0x77, 0x0f, 0xd3, 0x1f, 0x60, 0xb6,
	0xc9, 0xcb, 0xb6, 0x8d, 0x02, 0xef, 0x6c, 0x6c, 0xb4, 0xa0, 0x96, 0xda, 0xf4, 0x81, 0x03, 0x48,
	0xff, 0x1e, 0xc2, 0xe8, 0xc2, 0xaa, 0x02, 0xb9, 0x37, 0x3b, 0x6b, 0x51, 0x17, 0xeb, 0x58, 0xe6,
	0x0d, 0x16, 0x4f, 0x00, 0x96, 0xd2, 0x61, 0xde, 0x92, 0x93, 0x03, 0x0c, 0xb3, 0x19, 0x31, 0x61,
	0xea, 0xa7, 0xb0, 0x28, 0x6a, 0x94, 0x5a, 0xe9, 0x2a, 0xbf, 0xc2, 0xd0, 0xbf, 0xc3, 0x6c, 0xde,
	0x73, 0xa7, 0x88, 0xe2, 0x18, 0xf6, 0xf1, 0xad, 0xb7, 0x32, 0x6f, 0xd1, 0x3a, 0xa3, 0xd9, 0xb6,
	0xcb, 0xb6, 0x3d, 0xe6, 0x2f, 0x98, 0x26, 0xe7, 0x33, 0xb8, 0xfb, 0x06, 0xf1, 0xba, 0x5e, 0x87,
	0xd5, 0xf2, 0x2b, 0x59, 0x78, 0x13, 0xba, 0x7c, 0x98, 0xdd, 0x09, 0x12, 0x2f, 0x7b, 0xca, 0x02,
	0xf9, 0xa9, 0xaa, 0xff, 0xf7, 0x8f, 0x83, 0x3f, 0x48, 0xdb, 0xfe, 0x6f, 0xe1, 0xc0, 0x61, 0xd1,
	0x59, 0xe5, 0xd7, 0x79, 0x89, 0xad, 0x71, 0xca, 0xf3, 0x6e, 0x26, 0x3c, 0x41, 0xf4, 0xda, 0xcb,
	0x20, 0x9d, 0x22, 0xa6, 0xff, 0x0e, 0x60, 0x42, 0x17, 0x02, 0x9d, 0xa3, 0xd6, 0x91, 0xad, 0xef,
	0xef, 0xb4, 0x6c, 0x3d, 0x31, 0x75, 0x6c, 0xd4, 0x41, 0x46, 0x43, 0x66, 0x74, 0xc5, 0x59, 0x20,
	0x46, 0x57, 0xd4, 0x9a, 0x85, 0xf2, 0xeb, 0xd8, 0x5a, 0x3c, 0xa6, 0x7a, 0x38, 0x4f, 0xbd, 0x14,
	0xee, 0x6f, 0x00, 0xe2, 0x10, 0xc6, 0xce, 0x5b, 0x44, 0xdf, 0xdf, 0xde, 0x80, 0xa8, 0xae, 0x85,
	0xe9, 0xb4, 0xb7, 0xeb, 0x78, 0x7b, 0x7b, 0x48, 0xca, 0x3b, 0xd5, 0x16, 0xa6, 0xc4, 0x78, 0x7d,
	0x7b, 0x28, 0x52, 0x58, 0x68, 0x54, 0xd5, 0x6a, 0x69, 0xec, 0xca, 0x98, 0x32, 0x99, 0xb1, 0x7c,
	0x83, 0x4b, 0xff, 0x1c, 0xc0, 0xe4, 0x42, 0x15, 0xbe, 0xb3, 0x28, 0x1e, 0xc1, 0xac, 0x96, 0xb6,
	0x42, 0xbe, 0xd1, 0xb1, 0x05, 0x98, 0xb8, 0xb4, 0xb5, 0x78, 0x0a, 0x73, 0x8b, 0x55, 0x57, 0x4b,
	0xbb, 0x75, 0xe1, 0x21, 0x52, 0x64, 0xf8, 0x0c, 0x6e, 0xf9, 0x55, 0xd7, 0x2c, 0xb5, 0x54, 0x35,
	0x5b, 0xc2, 0x2b, 0xb6, 0xd8, 0x90, 0x64, 0xa2, 0x63, 0xc8, 0xd6, 0x2b, 0xa3, 0x63, 0x2e, 0x7a,
	0x98, 0xfe, 0x35, 0x85, 0xc9, 0xb9, 0x72, 0x5e, 0xe9, 0x4a, 0xec, 0xc1, 0x50, 0x95, 0xb1, 0x7f,
	0x87, 0xaa, 0xa4, 0xf4, 0x2d, 0xb1, 0xec, 0x3b, 0x97, 0xc7, 0xc4, 0x79, 0x59, 0xb9, 0xb8, 0x0a,
	0x8f, 0x99, 0x5b, 0xb7, 0xfd, 0x0d, 0xe6, 0xb1, 0xf8, 0x02, 0x6e, 0x7b, 0xb4, 0x8d, 0xcb, 0x1b,
	0xf9, 0x56, 0xab, 0x6a, 0xe5, 0x5d, 0x4c, 0xf8, 0x1e, 0xd3, 0xbf, 0xf4, 0xec, 0x96, 0x51, 0xe9,
	0x68, 0x1c, 0x6f, 0x1b, 0x7b, 0x56, 0x7c, 0x0d, 0x22, 0x18, 0x0b, 0xa9, 0x0b, 0xac, 0x6b, 0xc9,
	0xc7, 0x09, 0x55, 0xb9, 0xc3, 0xca, 0xc9, 0x96, 0x40, 0x75, 0xf6, 0xca, 0xd7, 0x7d, 0x75, 0x02,
	0xa0, 0x3a, 0xcb, 0xc2, 0xab, 0xd7, 0xc8, 0x55, 0x99, 0x66, 0x11, 0x89, 0x14, 0x46, 0xe1, 0x92,
	0x01, 0x3f, 0x20, 0x8b, 0xf8, 0x80, 0x70, 0x03, 0x67, 0x41, 0x12, 0xc7, 0x30, 0x91, 0xa1, 0x1d,
	0x93, 0x39, 0xbb, 0xf6, 0xa2, 0x2b, 0x36, 0x69, 0xd6, 0xcb, 0x94, 0xee, 0x25, 0x96, 0x9c, 0x93,
	0x45, 0x48, 0x77, 0x84, 0xe2, 0x4b, 0x98, 0xb6, 0xa1, 0xec, 0x2e, 0xb9, 0x75, 0xb4, 0xb3, 0x15,
	0x24, 0x76, 0x43, 0xb6, 0xd1, 0xe9, 0x65, 0x58, 0x62, 0x69, 0x8d, 0x69, 0x5c, 0xb2, 0xc7, 0x25,
	0xd8, 0x60, 0xf1, 0x18, 0x66, 0x4b, 0xe9, 0x57, 0x41, 0xbc, 0xcd, 0xe2, 0x7b, 0x82, 0x66, 0x2a,
	0x57, 0x2b, 0x47, 0x8f, 0xff, 0x3e, 0x9f, 0x73, 0x83, 0x49, 0xd3, 0xaa, 0xb8, 0xe6, 0xcf, 0xca,
	0x9d, 0xd0, 0x6c, 0x3d, 0xbe, 0xf1, 0x1c, 0x8b, 0x9b, 0xcf, 0xb1, 0x38, 0x82, 0xb9, 0x2c, 0x0a,
	0xd3, 0x18, 0x7a, 0x6f, 0x5d, 0x72, 0x8f, 0xd7, 0xdc, 0xa6, 0xa8, 0x55, 0x65, 0x5d, 0x9b, 0x37,
	0x2e, 0x6f, 0xd1, 0xbb, 0xe4, 0x90, 0x17, 0x86, 0x40, 0x5d, 0xa0, 0x77, 0xd4, 0xaa, 0xd1, 0x80,
	0xaf, 0x51, 0x7b, 0x97, 0xdc, 0x67, 0xcb, 0x22, 0x90, 0x3f, 0x33, 0x27, 0x3e, 0x87, 0xbd, 0x68,
	0x52, 0xfa, 0x4a, 0x92, 0x2b, 0x61, 0x57, 0x9c, 0x7a, 0x16, 0xc8, 0x2d, 0x9b, 0x6b, 0xcc, 0xb5,
	0xd2, 0x55, 0xf2, 0x60, 0xdb, 0xf6, 0x5b, 0x20, 0xa9, 0xbb, 0xa2, 0xad, 0x58, 0xa9, 0xba, 0xb4,
	0xa8, 0x93, 0x87, 0xec, 0x8b, 0xb3, 0x4f, 0x22, 0x2b, 0x7e, 0x84, 0x7b, 0x25, 0x5e, 0xc9, 0xae,
	0xf6, 0x79, 0xb1, 0xc2, 0xe2, 0x3a, 0x57, 0x3a, 0xe7, 0x2f, 0xca, 0xa3, 0x0f, 0xbf, 0x28, 0x22,
	0x3a, 0x4f, 0xc8, 0x78, 0xa6, 0xf9, 0xbb, 0xf2, 0x13, 0x1c, 0xde, 0x9c, 0x6f, 0x3a, 0x1f, 0x02,
	0x3c, 0xfe, 0x30, 0xc0, 0xdd, 0xed, 0x00, 0xbf, 0x76, 0x9e, 0x23, 0x7c, 0x05, 0x33, 0xc9, 0x9f,
	0x7d, 0x85, 0x2e, 0x79, 0x72, 0xa3, 0x37, 0xe2, 0xdf, 0x81, 0xec, 0xbd, 0x41, 0xbc, 0x84, 0xc3,
	0x0d, 0xc8, 0xb5, 0xf1, 0xb9, 0xd2, 0x45, 0xdd, 0x95, 0x58, 0x26, 0x9f, 0x7c, 0x74, 0xea, 0xc1,
	0xc6, 0xfd, 0xca, 0xf8, 0xb3, 0xe8, 0x15, 0x8f, 0x61, 0xa7, 0x36, 0x55, 0x52, 0xf2, 0x16, 0x21,
	0x4e, 0x39, 0x37, 0x55, 0x46, 0xf4, 0x72, 0xcc, 0xf8, 0xf9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0x12, 0x01, 0xaf, 0x71, 0x09, 0x00, 0x00,
}
