// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListingRequest struct {
	Listing              *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListingRequest) Reset()         { *m = GetListingRequest{} }
func (m *GetListingRequest) String() string { return proto.CompactTextString(m) }
func (*GetListingRequest) ProtoMessage()    {}
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *GetListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingRequest.Unmarshal(m, b)
}
func (m *GetListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingRequest.Marshal(b, m, deterministic)
}
func (m *GetListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingRequest.Merge(m, src)
}
func (m *GetListingRequest) XXX_Size() int {
	return xxx_messageInfo_GetListingRequest.Size(m)
}
func (m *GetListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingRequest proto.InternalMessageInfo

func (m *GetListingRequest) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

type CreateListingRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateListingRequest) Reset()         { *m = CreateListingRequest{} }
func (m *CreateListingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateListingRequest) ProtoMessage()    {}
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *CreateListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateListingRequest.Unmarshal(m, b)
}
func (m *CreateListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateListingRequest.Marshal(b, m, deterministic)
}
func (m *CreateListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateListingRequest.Merge(m, src)
}
func (m *CreateListingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateListingRequest.Size(m)
}
func (m *CreateListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateListingRequest proto.InternalMessageInfo

func (m *CreateListingRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateListingRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateListingRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateListingRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateListingRequest) Reset()         { *m = UpdateListingRequest{} }
func (m *UpdateListingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateListingRequest) ProtoMessage()    {}
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{2}
}

func (m *UpdateListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateListingRequest.Unmarshal(m, b)
}
func (m *UpdateListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateListingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateListingRequest.Merge(m, src)
}
func (m *UpdateListingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateListingRequest.Size(m)
}
func (m *UpdateListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateListingRequest proto.InternalMessageInfo

func (m *UpdateListingRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateListingRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateListingRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteListingRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteListingRequest) Reset()         { *m = DeleteListingRequest{} }
func (m *DeleteListingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteListingRequest) ProtoMessage()    {}
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{3}
}

func (m *DeleteListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteListingRequest.Unmarshal(m, b)
}
func (m *DeleteListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteListingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteListingRequest.Merge(m, src)
}
func (m *DeleteListingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteListingRequest.Size(m)
}
func (m *DeleteListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteListingRequest proto.InternalMessageInfo

func (m *DeleteListingRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteListingRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteListingRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetReservationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReservationRequest) Reset()         { *m = GetReservationRequest{} }
func (m *GetReservationRequest) String() string { return proto.CompactTextString(m) }
func (*GetReservationRequest) ProtoMessage()    {}
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{4}
}

func (m *GetReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationRequest.Unmarshal(m, b)
}
func (m *GetReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationRequest.Marshal(b, m, deterministic)
}
func (m *GetReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationRequest.Merge(m, src)
}
func (m *GetReservationRequest) XXX_Size() int {
	return xxx_messageInfo_GetReservationRequest.Size(m)
}
func (m *GetReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationRequest proto.InternalMessageInfo

func (m *GetReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetReservationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetReservationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateReservationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReservationRequest) Reset()         { *m = CreateReservationRequest{} }
func (m *CreateReservationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReservationRequest) ProtoMessage()    {}
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{5}
}

func (m *CreateReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReservationRequest.Unmarshal(m, b)
}
func (m *CreateReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReservationRequest.Marshal(b, m, deterministic)
}
func (m *CreateReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReservationRequest.Merge(m, src)
}
func (m *CreateReservationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReservationRequest.Size(m)
}
func (m *CreateReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReservationRequest proto.InternalMessageInfo

func (m *CreateReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateReservationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateReservationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateReservationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReservationRequest) Reset()         { *m = UpdateReservationRequest{} }
func (m *UpdateReservationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateReservationRequest) ProtoMessage()    {}
func (*UpdateReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{6}
}

func (m *UpdateReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReservationRequest.Unmarshal(m, b)
}
func (m *UpdateReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReservationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReservationRequest.Merge(m, src)
}
func (m *UpdateReservationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateReservationRequest.Size(m)
}
func (m *UpdateReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReservationRequest proto.InternalMessageInfo

func (m *UpdateReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateReservationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateReservationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteReservationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationRequest) Reset()         { *m = DeleteReservationRequest{} }
func (m *DeleteReservationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationRequest) ProtoMessage()    {}
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{7}
}

func (m *DeleteReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationRequest.Unmarshal(m, b)
}
func (m *DeleteReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationRequest.Merge(m, src)
}
func (m *DeleteReservationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationRequest.Size(m)
}
func (m *DeleteReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationRequest proto.InternalMessageInfo

func (m *DeleteReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteReservationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteReservationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetGuestRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGuestRequest) Reset()         { *m = GetGuestRequest{} }
func (m *GetGuestRequest) String() string { return proto.CompactTextString(m) }
func (*GetGuestRequest) ProtoMessage()    {}
func (*GetGuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{8}
}

func (m *GetGuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGuestRequest.Unmarshal(m, b)
}
func (m *GetGuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGuestRequest.Marshal(b, m, deterministic)
}
func (m *GetGuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGuestRequest.Merge(m, src)
}
func (m *GetGuestRequest) XXX_Size() int {
	return xxx_messageInfo_GetGuestRequest.Size(m)
}
func (m *GetGuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGuestRequest proto.InternalMessageInfo

func (m *GetGuestRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetGuestRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetGuestRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateGuestRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGuestRequest) Reset()         { *m = CreateGuestRequest{} }
func (m *CreateGuestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGuestRequest) ProtoMessage()    {}
func (*CreateGuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{9}
}

func (m *CreateGuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestRequest.Unmarshal(m, b)
}
func (m *CreateGuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestRequest.Marshal(b, m, deterministic)
}
func (m *CreateGuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestRequest.Merge(m, src)
}
func (m *CreateGuestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGuestRequest.Size(m)
}
func (m *CreateGuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestRequest proto.InternalMessageInfo

func (m *CreateGuestRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateGuestRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateGuestRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateGuestRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGuestRequest) Reset()         { *m = UpdateGuestRequest{} }
func (m *UpdateGuestRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGuestRequest) ProtoMessage()    {}
func (*UpdateGuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{10}
}

func (m *UpdateGuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGuestRequest.Unmarshal(m, b)
}
func (m *UpdateGuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGuestRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGuestRequest.Merge(m, src)
}
func (m *UpdateGuestRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGuestRequest.Size(m)
}
func (m *UpdateGuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGuestRequest proto.InternalMessageInfo

func (m *UpdateGuestRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateGuestRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateGuestRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteGuestRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGuestRequest) Reset()         { *m = DeleteGuestRequest{} }
func (m *DeleteGuestRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGuestRequest) ProtoMessage()    {}
func (*DeleteGuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{11}
}

func (m *DeleteGuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGuestRequest.Unmarshal(m, b)
}
func (m *DeleteGuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGuestRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGuestRequest.Merge(m, src)
}
func (m *DeleteGuestRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGuestRequest.Size(m)
}
func (m *DeleteGuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGuestRequest proto.InternalMessageInfo

func (m *DeleteGuestRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteGuestRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteGuestRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetCalendarRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCalendarRequest) Reset()         { *m = GetCalendarRequest{} }
func (m *GetCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*GetCalendarRequest) ProtoMessage()    {}
func (*GetCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{12}
}

func (m *GetCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalendarRequest.Unmarshal(m, b)
}
func (m *GetCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalendarRequest.Marshal(b, m, deterministic)
}
func (m *GetCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalendarRequest.Merge(m, src)
}
func (m *GetCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_GetCalendarRequest.Size(m)
}
func (m *GetCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalendarRequest proto.InternalMessageInfo

func (m *GetCalendarRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetCalendarRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetCalendarRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateCalendarRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCalendarRequest) Reset()         { *m = CreateCalendarRequest{} }
func (m *CreateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCalendarRequest) ProtoMessage()    {}
func (*CreateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{13}
}

func (m *CreateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCalendarRequest.Unmarshal(m, b)
}
func (m *CreateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *CreateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCalendarRequest.Merge(m, src)
}
func (m *CreateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCalendarRequest.Size(m)
}
func (m *CreateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCalendarRequest proto.InternalMessageInfo

func (m *CreateCalendarRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateCalendarRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateCalendarRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateCalendarRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCalendarRequest) Reset()         { *m = UpdateCalendarRequest{} }
func (m *UpdateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCalendarRequest) ProtoMessage()    {}
func (*UpdateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{14}
}

func (m *UpdateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCalendarRequest.Unmarshal(m, b)
}
func (m *UpdateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCalendarRequest.Merge(m, src)
}
func (m *UpdateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCalendarRequest.Size(m)
}
func (m *UpdateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCalendarRequest proto.InternalMessageInfo

func (m *UpdateCalendarRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCalendarRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateCalendarRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteCalendarRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCalendarRequest) Reset()         { *m = DeleteCalendarRequest{} }
func (m *DeleteCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCalendarRequest) ProtoMessage()    {}
func (*DeleteCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{15}
}

func (m *DeleteCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCalendarRequest.Unmarshal(m, b)
}
func (m *DeleteCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCalendarRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCalendarRequest.Merge(m, src)
}
func (m *DeleteCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCalendarRequest.Size(m)
}
func (m *DeleteCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCalendarRequest proto.InternalMessageInfo

func (m *DeleteCalendarRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteCalendarRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteCalendarRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetConversationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationRequest) Reset()         { *m = GetConversationRequest{} }
func (m *GetConversationRequest) String() string { return proto.CompactTextString(m) }
func (*GetConversationRequest) ProtoMessage()    {}
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{16}
}

func (m *GetConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationRequest.Unmarshal(m, b)
}
func (m *GetConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationRequest.Marshal(b, m, deterministic)
}
func (m *GetConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationRequest.Merge(m, src)
}
func (m *GetConversationRequest) XXX_Size() int {
	return xxx_messageInfo_GetConversationRequest.Size(m)
}
func (m *GetConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationRequest proto.InternalMessageInfo

func (m *GetConversationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetConversationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetConversationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateConversationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationRequest) Reset()         { *m = CreateConversationRequest{} }
func (m *CreateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConversationRequest) ProtoMessage()    {}
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{17}
}

func (m *CreateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationRequest.Unmarshal(m, b)
}
func (m *CreateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationRequest.Marshal(b, m, deterministic)
}
func (m *CreateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationRequest.Merge(m, src)
}
func (m *CreateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConversationRequest.Size(m)
}
func (m *CreateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationRequest proto.InternalMessageInfo

func (m *CreateConversationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateConversationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateConversationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateConversationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConversationRequest) Reset()         { *m = UpdateConversationRequest{} }
func (m *UpdateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationRequest) ProtoMessage()    {}
func (*UpdateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{18}
}

func (m *UpdateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationRequest.Unmarshal(m, b)
}
func (m *UpdateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationRequest.Merge(m, src)
}
func (m *UpdateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationRequest.Size(m)
}
func (m *UpdateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationRequest proto.InternalMessageInfo

func (m *UpdateConversationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateConversationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateConversationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteConversationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConversationRequest) Reset()         { *m = DeleteConversationRequest{} }
func (m *DeleteConversationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteConversationRequest) ProtoMessage()    {}
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{19}
}

func (m *DeleteConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConversationRequest.Unmarshal(m, b)
}
func (m *DeleteConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConversationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConversationRequest.Merge(m, src)
}
func (m *DeleteConversationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteConversationRequest.Size(m)
}
func (m *DeleteConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConversationRequest proto.InternalMessageInfo

func (m *DeleteConversationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteConversationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteConversationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*GetListingRequest)(nil), "proto.GetListingRequest")
	proto.RegisterType((*CreateListingRequest)(nil), "proto.CreateListingRequest")
	proto.RegisterType((*UpdateListingRequest)(nil), "proto.UpdateListingRequest")
	proto.RegisterType((*DeleteListingRequest)(nil), "proto.DeleteListingRequest")
	proto.RegisterType((*GetReservationRequest)(nil), "proto.GetReservationRequest")
	proto.RegisterType((*CreateReservationRequest)(nil), "proto.CreateReservationRequest")
	proto.RegisterType((*UpdateReservationRequest)(nil), "proto.UpdateReservationRequest")
	proto.RegisterType((*DeleteReservationRequest)(nil), "proto.DeleteReservationRequest")
	proto.RegisterType((*GetGuestRequest)(nil), "proto.GetGuestRequest")
	proto.RegisterType((*CreateGuestRequest)(nil), "proto.CreateGuestRequest")
	proto.RegisterType((*UpdateGuestRequest)(nil), "proto.UpdateGuestRequest")
	proto.RegisterType((*DeleteGuestRequest)(nil), "proto.DeleteGuestRequest")
	proto.RegisterType((*GetCalendarRequest)(nil), "proto.GetCalendarRequest")
	proto.RegisterType((*CreateCalendarRequest)(nil), "proto.CreateCalendarRequest")
	proto.RegisterType((*UpdateCalendarRequest)(nil), "proto.UpdateCalendarRequest")
	proto.RegisterType((*DeleteCalendarRequest)(nil), "proto.DeleteCalendarRequest")
	proto.RegisterType((*GetConversationRequest)(nil), "proto.GetConversationRequest")
	proto.RegisterType((*CreateConversationRequest)(nil), "proto.CreateConversationRequest")
	proto.RegisterType((*UpdateConversationRequest)(nil), "proto.UpdateConversationRequest")
	proto.RegisterType((*DeleteConversationRequest)(nil), "proto.DeleteConversationRequest")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x46, 0x69, 0x17, 0x5d, 0x1d, 0x75, 0xc5, 0xa0, 0x12, 0xf7, 0xb4, 0xec, 0xa9, 0xa7, 0x3d,
	0xe8, 0xd9, 0xd3, 0x0a, 0xb9, 0x78, 0x2a, 0x88, 0x20, 0x2a, 0x46, 0x33, 0x48, 0xb0, 0x9b, 0xac,
	0xc9, 0xb8, 0xbf, 0x5f, 0xda, 0x69, 0x3d, 0x78, 0xee, 0x9c, 0x4a, 0x32, 0xd3, 0xf7, 0xc1, 0x1b,
	0x86, 0xc0, 0x49, 0xc2, 0xef, 0x1f, 0xcc, 0xb4, 0xda, 0xa6, 0x48, 0x51, 0xed, 0x75, 0x9f, 0xf9,
	0xf1, 0x26, 0x3a, 0x6c, 0x32, 0x5f, 0x2e, 0x6f, 0xe1, 0xcc, 0x20, 0xdd, 0xfb, 0x4c, 0x3e, 0x7c,
	0xd6, 0xdc, 0xaf, 0x2a, 0x98, 0x36, 0x7c, 0xa3, 0x8b, 0x45, 0x51, 0x1d, 0x5d, 0xcf, 0xb8, 0x7b,
	0x35, 0xf4, 0x0d, 0xe5, 0xe5, 0x33, 0x9c, 0xaf, 0x13, 0x5a, 0xc2, 0x7f, 0x84, 0x19, 0x94, 0xde,
	0x75, 0x3f, 0x4f, 0xea, 0xd2, 0x3b, 0x35, 0x87, 0x83, 0xe0, 0x3f, 0xbe, 0x82, 0xdd, 0xa0, 0x2e,
	0x17, 0x45, 0x75, 0x58, 0xff, 0x9d, 0x95, 0x86, 0xa9, 0x75, 0x2e, 0x61, 0xce, 0x7a, 0xd2, 0x95,
	0x86, 0x63, 0x4b, 0x7f, 0xd8, 0x3a, 0x41, 0xfa, 0x1d, 0x36, 0x28, 0x44, 0x7f, 0x81, 0x0b, 0x83,
	0x54, 0x63, 0xc6, 0xb4, 0xb3, 0xe4, 0x63, 0x18, 0x17, 0xff, 0x06, 0x9a, 0xc5, 0x4b, 0x26, 0xb0,
	0x7c, 0xc9, 0x04, 0x1e, 0x80, 0x58, 0xc2, 0x23, 0x9c, 0x1a, 0x24, 0xd3, 0x12, 0xc7, 0x05, 0x3f,
	0x81, 0x62, 0xfd, 0x32, 0x6c, 0x16, 0x2f, 0xc3, 0x66, 0xe5, 0x32, 0x6c, 0x83, 0xb4, 0xb6, 0x0d,
	0x06, 0x67, 0xd3, 0xe8, 0xdb, 0xc4, 0xbe, 0xc5, 0xf0, 0xac, 0x5c, 0x0c, 0xcf, 0xd6, 0x65, 0xf0,
	0xaf, 0x70, 0xd9, 0x8a, 0x8f, 0x61, 0x87, 0x29, 0x0b, 0x6c, 0x91, 0x85, 0xab, 0x5e, 0xbe, 0x64,
	0x44, 0x3f, 0x00, 0xc9, 0x88, 0x7e, 0x08, 0x52, 0x11, 0xef, 0xfb, 0xdd, 0x2b, 0x79, 0xf3, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xab, 0x79, 0xc5, 0xa1, 0x79, 0x07, 0x00, 0x00,
}
