// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListingResponse struct {
	Listing              *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListingResponse) Reset()         { *m = GetListingResponse{} }
func (m *GetListingResponse) String() string { return proto.CompactTextString(m) }
func (*GetListingResponse) ProtoMessage()    {}
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{0}
}

func (m *GetListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingResponse.Unmarshal(m, b)
}
func (m *GetListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingResponse.Marshal(b, m, deterministic)
}
func (m *GetListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingResponse.Merge(m, src)
}
func (m *GetListingResponse) XXX_Size() int {
	return xxx_messageInfo_GetListingResponse.Size(m)
}
func (m *GetListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingResponse proto.InternalMessageInfo

func (m *GetListingResponse) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

type CreateListingResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateListingResponse) Reset()         { *m = CreateListingResponse{} }
func (m *CreateListingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateListingResponse) ProtoMessage()    {}
func (*CreateListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{1}
}

func (m *CreateListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateListingResponse.Unmarshal(m, b)
}
func (m *CreateListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateListingResponse.Marshal(b, m, deterministic)
}
func (m *CreateListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateListingResponse.Merge(m, src)
}
func (m *CreateListingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateListingResponse.Size(m)
}
func (m *CreateListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateListingResponse proto.InternalMessageInfo

func (m *CreateListingResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateListingResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateListingResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateListingResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateListingResponse) Reset()         { *m = UpdateListingResponse{} }
func (m *UpdateListingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateListingResponse) ProtoMessage()    {}
func (*UpdateListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{2}
}

func (m *UpdateListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateListingResponse.Unmarshal(m, b)
}
func (m *UpdateListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateListingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateListingResponse.Merge(m, src)
}
func (m *UpdateListingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateListingResponse.Size(m)
}
func (m *UpdateListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateListingResponse proto.InternalMessageInfo

func (m *UpdateListingResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateListingResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateListingResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteListingResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteListingResponse) Reset()         { *m = DeleteListingResponse{} }
func (m *DeleteListingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteListingResponse) ProtoMessage()    {}
func (*DeleteListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{3}
}

func (m *DeleteListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteListingResponse.Unmarshal(m, b)
}
func (m *DeleteListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteListingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteListingResponse.Merge(m, src)
}
func (m *DeleteListingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteListingResponse.Size(m)
}
func (m *DeleteListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteListingResponse proto.InternalMessageInfo

func (m *DeleteListingResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteListingResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteListingResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetReservationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReservationResponse) Reset()         { *m = GetReservationResponse{} }
func (m *GetReservationResponse) String() string { return proto.CompactTextString(m) }
func (*GetReservationResponse) ProtoMessage()    {}
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{4}
}

func (m *GetReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationResponse.Unmarshal(m, b)
}
func (m *GetReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationResponse.Marshal(b, m, deterministic)
}
func (m *GetReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationResponse.Merge(m, src)
}
func (m *GetReservationResponse) XXX_Size() int {
	return xxx_messageInfo_GetReservationResponse.Size(m)
}
func (m *GetReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationResponse proto.InternalMessageInfo

func (m *GetReservationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetReservationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetReservationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateReservationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReservationResponse) Reset()         { *m = CreateReservationResponse{} }
func (m *CreateReservationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReservationResponse) ProtoMessage()    {}
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{5}
}

func (m *CreateReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReservationResponse.Unmarshal(m, b)
}
func (m *CreateReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReservationResponse.Marshal(b, m, deterministic)
}
func (m *CreateReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReservationResponse.Merge(m, src)
}
func (m *CreateReservationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReservationResponse.Size(m)
}
func (m *CreateReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReservationResponse proto.InternalMessageInfo

func (m *CreateReservationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateReservationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateReservationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateReservationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReservationResponse) Reset()         { *m = UpdateReservationResponse{} }
func (m *UpdateReservationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateReservationResponse) ProtoMessage()    {}
func (*UpdateReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{6}
}

func (m *UpdateReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReservationResponse.Unmarshal(m, b)
}
func (m *UpdateReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReservationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReservationResponse.Merge(m, src)
}
func (m *UpdateReservationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateReservationResponse.Size(m)
}
func (m *UpdateReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReservationResponse proto.InternalMessageInfo

func (m *UpdateReservationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateReservationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateReservationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteReservationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationResponse) Reset()         { *m = DeleteReservationResponse{} }
func (m *DeleteReservationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationResponse) ProtoMessage()    {}
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{7}
}

func (m *DeleteReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationResponse.Unmarshal(m, b)
}
func (m *DeleteReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationResponse.Merge(m, src)
}
func (m *DeleteReservationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationResponse.Size(m)
}
func (m *DeleteReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationResponse proto.InternalMessageInfo

func (m *DeleteReservationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteReservationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteReservationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetGuestResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGuestResponse) Reset()         { *m = GetGuestResponse{} }
func (m *GetGuestResponse) String() string { return proto.CompactTextString(m) }
func (*GetGuestResponse) ProtoMessage()    {}
func (*GetGuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{8}
}

func (m *GetGuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGuestResponse.Unmarshal(m, b)
}
func (m *GetGuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGuestResponse.Marshal(b, m, deterministic)
}
func (m *GetGuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGuestResponse.Merge(m, src)
}
func (m *GetGuestResponse) XXX_Size() int {
	return xxx_messageInfo_GetGuestResponse.Size(m)
}
func (m *GetGuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGuestResponse proto.InternalMessageInfo

func (m *GetGuestResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetGuestResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetGuestResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateGuestResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGuestResponse) Reset()         { *m = CreateGuestResponse{} }
func (m *CreateGuestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGuestResponse) ProtoMessage()    {}
func (*CreateGuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{9}
}

func (m *CreateGuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestResponse.Unmarshal(m, b)
}
func (m *CreateGuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestResponse.Marshal(b, m, deterministic)
}
func (m *CreateGuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestResponse.Merge(m, src)
}
func (m *CreateGuestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGuestResponse.Size(m)
}
func (m *CreateGuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestResponse proto.InternalMessageInfo

func (m *CreateGuestResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateGuestResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateGuestResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateGuestResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGuestResponse) Reset()         { *m = UpdateGuestResponse{} }
func (m *UpdateGuestResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGuestResponse) ProtoMessage()    {}
func (*UpdateGuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{10}
}

func (m *UpdateGuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGuestResponse.Unmarshal(m, b)
}
func (m *UpdateGuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGuestResponse.Marshal(b, m, deterministic)
}
func (m *UpdateGuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGuestResponse.Merge(m, src)
}
func (m *UpdateGuestResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGuestResponse.Size(m)
}
func (m *UpdateGuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGuestResponse proto.InternalMessageInfo

func (m *UpdateGuestResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateGuestResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateGuestResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteGuestResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGuestResponse) Reset()         { *m = DeleteGuestResponse{} }
func (m *DeleteGuestResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGuestResponse) ProtoMessage()    {}
func (*DeleteGuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{11}
}

func (m *DeleteGuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGuestResponse.Unmarshal(m, b)
}
func (m *DeleteGuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGuestResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGuestResponse.Merge(m, src)
}
func (m *DeleteGuestResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGuestResponse.Size(m)
}
func (m *DeleteGuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGuestResponse proto.InternalMessageInfo

func (m *DeleteGuestResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteGuestResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteGuestResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetCalendarResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCalendarResponse) Reset()         { *m = GetCalendarResponse{} }
func (m *GetCalendarResponse) String() string { return proto.CompactTextString(m) }
func (*GetCalendarResponse) ProtoMessage()    {}
func (*GetCalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{12}
}

func (m *GetCalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalendarResponse.Unmarshal(m, b)
}
func (m *GetCalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalendarResponse.Marshal(b, m, deterministic)
}
func (m *GetCalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalendarResponse.Merge(m, src)
}
func (m *GetCalendarResponse) XXX_Size() int {
	return xxx_messageInfo_GetCalendarResponse.Size(m)
}
func (m *GetCalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalendarResponse proto.InternalMessageInfo

func (m *GetCalendarResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetCalendarResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetCalendarResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateCalendarResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCalendarResponse) Reset()         { *m = CreateCalendarResponse{} }
func (m *CreateCalendarResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCalendarResponse) ProtoMessage()    {}
func (*CreateCalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{13}
}

func (m *CreateCalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCalendarResponse.Unmarshal(m, b)
}
func (m *CreateCalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCalendarResponse.Marshal(b, m, deterministic)
}
func (m *CreateCalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCalendarResponse.Merge(m, src)
}
func (m *CreateCalendarResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCalendarResponse.Size(m)
}
func (m *CreateCalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCalendarResponse proto.InternalMessageInfo

func (m *CreateCalendarResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateCalendarResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateCalendarResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateCalendarResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCalendarResponse) Reset()         { *m = UpdateCalendarResponse{} }
func (m *UpdateCalendarResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCalendarResponse) ProtoMessage()    {}
func (*UpdateCalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{14}
}

func (m *UpdateCalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCalendarResponse.Unmarshal(m, b)
}
func (m *UpdateCalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCalendarResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCalendarResponse.Merge(m, src)
}
func (m *UpdateCalendarResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCalendarResponse.Size(m)
}
func (m *UpdateCalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCalendarResponse proto.InternalMessageInfo

func (m *UpdateCalendarResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCalendarResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateCalendarResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteCalendarResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCalendarResponse) Reset()         { *m = DeleteCalendarResponse{} }
func (m *DeleteCalendarResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCalendarResponse) ProtoMessage()    {}
func (*DeleteCalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{15}
}

func (m *DeleteCalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCalendarResponse.Unmarshal(m, b)
}
func (m *DeleteCalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCalendarResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCalendarResponse.Merge(m, src)
}
func (m *DeleteCalendarResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCalendarResponse.Size(m)
}
func (m *DeleteCalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCalendarResponse proto.InternalMessageInfo

func (m *DeleteCalendarResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteCalendarResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteCalendarResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetConversationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationResponse) Reset()         { *m = GetConversationResponse{} }
func (m *GetConversationResponse) String() string { return proto.CompactTextString(m) }
func (*GetConversationResponse) ProtoMessage()    {}
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{16}
}

func (m *GetConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationResponse.Unmarshal(m, b)
}
func (m *GetConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationResponse.Marshal(b, m, deterministic)
}
func (m *GetConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationResponse.Merge(m, src)
}
func (m *GetConversationResponse) XXX_Size() int {
	return xxx_messageInfo_GetConversationResponse.Size(m)
}
func (m *GetConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationResponse proto.InternalMessageInfo

func (m *GetConversationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetConversationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetConversationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateConversationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationResponse) Reset()         { *m = CreateConversationResponse{} }
func (m *CreateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResponse) ProtoMessage()    {}
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{17}
}

func (m *CreateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResponse.Unmarshal(m, b)
}
func (m *CreateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResponse.Marshal(b, m, deterministic)
}
func (m *CreateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResponse.Merge(m, src)
}
func (m *CreateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResponse.Size(m)
}
func (m *CreateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResponse proto.InternalMessageInfo

func (m *CreateConversationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateConversationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateConversationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateConversationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConversationResponse) Reset()         { *m = UpdateConversationResponse{} }
func (m *UpdateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationResponse) ProtoMessage()    {}
func (*UpdateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{18}
}

func (m *UpdateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationResponse.Unmarshal(m, b)
}
func (m *UpdateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationResponse.Merge(m, src)
}
func (m *UpdateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationResponse.Size(m)
}
func (m *UpdateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationResponse proto.InternalMessageInfo

func (m *UpdateConversationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateConversationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateConversationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteConversationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConversationResponse) Reset()         { *m = DeleteConversationResponse{} }
func (m *DeleteConversationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteConversationResponse) ProtoMessage()    {}
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{19}
}

func (m *DeleteConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConversationResponse.Unmarshal(m, b)
}
func (m *DeleteConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConversationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConversationResponse.Merge(m, src)
}
func (m *DeleteConversationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteConversationResponse.Size(m)
}
func (m *DeleteConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConversationResponse proto.InternalMessageInfo

func (m *DeleteConversationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteConversationResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DeleteConversationResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*GetListingResponse)(nil), "proto.GetListingResponse")
	proto.RegisterType((*CreateListingResponse)(nil), "proto.CreateListingResponse")
	proto.RegisterType((*UpdateListingResponse)(nil), "proto.UpdateListingResponse")
	proto.RegisterType((*DeleteListingResponse)(nil), "proto.DeleteListingResponse")
	proto.RegisterType((*GetReservationResponse)(nil), "proto.GetReservationResponse")
	proto.RegisterType((*CreateReservationResponse)(nil), "proto.CreateReservationResponse")
	proto.RegisterType((*UpdateReservationResponse)(nil), "proto.UpdateReservationResponse")
	proto.RegisterType((*DeleteReservationResponse)(nil), "proto.DeleteReservationResponse")
	proto.RegisterType((*GetGuestResponse)(nil), "proto.GetGuestResponse")
	proto.RegisterType((*CreateGuestResponse)(nil), "proto.CreateGuestResponse")
	proto.RegisterType((*UpdateGuestResponse)(nil), "proto.UpdateGuestResponse")
	proto.RegisterType((*DeleteGuestResponse)(nil), "proto.DeleteGuestResponse")
	proto.RegisterType((*GetCalendarResponse)(nil), "proto.GetCalendarResponse")
	proto.RegisterType((*CreateCalendarResponse)(nil), "proto.CreateCalendarResponse")
	proto.RegisterType((*UpdateCalendarResponse)(nil), "proto.UpdateCalendarResponse")
	proto.RegisterType((*DeleteCalendarResponse)(nil), "proto.DeleteCalendarResponse")
	proto.RegisterType((*GetConversationResponse)(nil), "proto.GetConversationResponse")
	proto.RegisterType((*CreateConversationResponse)(nil), "proto.CreateConversationResponse")
	proto.RegisterType((*UpdateConversationResponse)(nil), "proto.UpdateConversationResponse")
	proto.RegisterType((*DeleteConversationResponse)(nil), "proto.DeleteConversationResponse")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_0fbc901015fa5021) }

var fileDescriptor_0fbc901015fa5021 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x49, 0x0e, 0x3d, 0x1d, 0x25, 0xc8, 0x8a, 0x1a, 0x53, 0x1d, 0x57, 0xa5, 0xba, 0x42,
	0x7b, 0x9b, 0x13, 0xb6, 0xb1, 0x0a, 0x08, 0x82, 0xa8, 0xec, 0xb9, 0x83, 0x2c, 0xe6, 0x76, 0xc3,
	0xee, 0x78, 0x9f, 0x5f, 0x92, 0x49, 0x2c, 0xac, 0x33, 0x55, 0xd8, 0xf9, 0xf3, 0x7b, 0xf0, 0x1e,
	0x43, 0xa0, 0x88, 0x98, 0xba, 0xe0, 0x13, 0x6e, 0xba, 0x18, 0x28, 0xa8, 0xa3, 0xe1, 0x53, 0x9d,
	0xef, 0x83, 0xc5, 0x36, 0x71, 0x71, 0xfd, 0x00, 0x4a, 0x23, 0x3d, 0xb9, 0x44, 0xce, 0x7f, 0x35,
	0xe3, 0x82, 0xaa, 0x61, 0xd9, 0x72, 0xa9, 0xcc, 0x56, 0x59, 0x7d, 0x76, 0x57, 0xf0, 0xf8, 0x66,
	0x1a, 0x9c, 0xda, 0xeb, 0x37, 0xb8, 0xda, 0x46, 0x34, 0x84, 0xff, 0x11, 0x05, 0xe4, 0xce, 0x0e,
	0xdb, 0x8b, 0x26, 0x77, 0x56, 0x55, 0x70, 0xe2, 0xdd, 0xe7, 0xb7, 0x37, 0x7b, 0x2c, 0xf3, 0x55,
	0x56, 0x9f, 0x36, 0x7f, 0x6f, 0x55, 0xc2, 0xd2, 0x58, 0x1b, 0x31, 0xa5, 0x72, 0x31, 0xb4, 0xa6,
	0x67, 0x8f, 0x7f, 0xee, 0xac, 0x24, 0xfe, 0x11, 0x5b, 0x94, 0xc2, 0xbf, 0xc3, 0xb5, 0x46, 0x6a,
	0x30, 0x61, 0x3c, 0x18, 0x72, 0xc1, 0xcf, 0xcc, 0x37, 0x70, 0xcb, 0xe6, 0x8b, 0x4a, 0x70, 0x00,
	0xa2, 0x12, 0x1c, 0x82, 0x9c, 0xc4, 0x0b, 0x5c, 0x68, 0x24, 0xfd, 0x83, 0x89, 0x66, 0x26, 0xbf,
	0xc2, 0x25, 0x47, 0x20, 0x04, 0x67, 0xf3, 0x85, 0xe0, 0x6c, 0xbb, 0x10, 0x5c, 0x23, 0x6d, 0x4d,
	0x8b, 0xde, 0x9a, 0x38, 0xff, 0x59, 0xb1, 0xe7, 0x72, 0x7c, 0xb6, 0x5d, 0x8e, 0xcf, 0xce, 0x0b,
	0xf1, 0x3f, 0xe0, 0xa6, 0x37, 0x3f, 0xf8, 0x03, 0xc6, 0x24, 0x71, 0x4e, 0x3b, 0xa8, 0xc6, 0x00,
	0x44, 0x35, 0xc6, 0x10, 0x44, 0x35, 0xc6, 0x20, 0xc4, 0x34, 0x76, 0xc7, 0xc3, 0x8f, 0xf3, 0xfe,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xae, 0x06, 0xe8, 0x8e, 0x07, 0x00, 0x00,
}
